name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

# These permissions are required for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact (static site)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          # "dist" is Astro's default build output folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # "pages" + "id-token" permissions are defined at the top
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          folder: dist
